languageCode = "en-us"
title = "FiveM Documentation"
theme = "docsy"
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
baseURL = "/"
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

disablePathToLower = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
disableHomeIcon = true
editURL = "https://github.com/citizenfx/fivem-docs/edit/master/content/"
github_repo = "https://github.com/citizenfx/fivem-docs"
github_project_repo = "https://github.com/citizenfx/fivem"
offlineSearch = true

[blackfriday]
hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "<svg id='snail' viewBox='0 0 64 64' width='32px' height='32px'> <path d='m29.6 42.8c0 0-4.7-20.8-13.1-20.8-15.1 0-15.5 27.8-5.3 37 3.1 2.8 16.1 2.8 43.5 0 2.9-.3 1.8-3.1-2.3-5-2.7-1.3-15.8-3.7-22.8-11.2' fill='#94d82a'></path><g fill='#769e2a'><ellipse cx='27.8' cy='39.8' rx='3.9' ry='6.7'></ellipse><ellipse cx='31.5' cy='53.4' rx='2.4' ry='2.7'></ellipse><ellipse cx='22.5' cy='48.5' rx='1.8' ry='3.1'></ellipse><ellipse cx='20.2' cy='36.4' rx='1.4' ry='2.1'></ellipse></g><path d='m9.6 26.1c0 1.2.4 2.3 1.1 2.9.3.3.7.5 1.1.7.2.1.4.1.6.1 0 0 .3 0 .4 0 .1 0 .2 0 .3 0 .9 0 1.8-.3 2.5-.9.7-.6 1.2-1.6 1.6-2.8.4 1.2.4 2.6-.4 3.8-.8 1.2-2.3 1.9-3.7 1.9-.2 0-.3 0-.5 0-.2 0-.3 0-.5-.1-.4-.1-.7-.2-1.1-.3-.7-.3-1.3-.8-1.6-1.5-.7-1.2-.6-2.8.2-3.8' fill='#3e4347'></path><path d='m58.9 42.3c3.4-4.3 3.9-11.2 2-15.4-2.8-6.2-8.3-7.1-8.3-7.1-7.4-11.9-27.8-11.9-34 2.7 5.3 3.1 8.3 11.8 10 16.5 1.6 6.3 4.7 12 9.8 13.5 2.2.6 2.6-1.7 2.6-1.7 1.4 2 4.3 3.4 6.9 2.7 9.7-2.8 11-11.2 11-11.2' fill='#e08828'></path><g fill='#94d82a'><path d='m14.5 24.2l-2.6.9-2.5-6.9 2.6-.9z'></path><path d='m20.3 26.8l-2.5-1.1 3.1-6.7 2.5 1.2z'></path><path d='m19 12.7c0 4.7-3.8 8.5-8.5 8.5-4.7 0-8.5-3.8-8.5-8.5 0-4.7 3.8-8.5 8.5-8.5 4.7.1 8.5 3.9 8.5 8.5'></path></g><path d='m15.4 13c0 3.7-2.9 6.6-6.4 6.6-3.6 0-6.4-3-6.4-6.6 0-3.7 2.9-6.6 6.4-6.6 3.5 0 6.4 3 6.4 6.6' fill='#fcfcfa'></path><path d='m14.6 13c0 2.5-2 4.6-4.4 4.6-2.4 0-4.4-2-4.4-4.6 0-2.5 2-4.6 4.4-4.6 2.5.1 4.4 2.1 4.4 4.6' fill='#3e4347'></path><g fill='#93603b'><path d='m41.1 50.7c-1.9-2.9-3.3-6.2-4-9.6-.7-3.5-.7-7.1.1-10.6.8-3.5 2.5-6.9 5.3-9.3 1.4-1.2 3.1-2 4.9-2.3 1.8-.3 3.6 0 5.2.8-1.7-.4-3.4-.4-5 .1-1.6.5-2.9 1.4-4.1 2.5-1.1 1.1-2.1 2.5-2.8 4-.7 1.5-1.3 3-1.6 4.6-.8 3.2-.9 6.6-.5 9.9.5 3.4 1.3 6.7 2.5 9.9'></path><path d='m58.9 42.3c-.7.9-1.6 1.6-2.6 2.2-1 .6-2.1 1-3.4 1.1-1.2.1-2.5-.3-3.6-1-1.1-.7-1.9-1.6-2.6-2.6-1.4-2-1.9-4.7-1.6-7.1.3-2.4 1.4-4.8 3.1-6.6.9-.9 1.9-1.7 3.2-2.1 1.2-.5 2.6-.6 3.9-.2 1.4.4 2.5 1.4 3.1 2.5.6 1.2.9 2.5.8 3.8-.1 1.3-.5 2.6-1.5 3.5-.9 1-2.5 1.5-3.8.8-1.3-.7-1.9-2.1-1.6-3.4.2-.7.6-1.2 1.2-1.5.3-.1.7-.2 1 0 .3.1.5.3.7.6-1-.9-2 .3-2.1 1.1-.1.9.5 1.9 1.3 2.2.4.2.8.1 1.3 0 .4-.1.8-.4 1.1-.7.6-.7.9-1.7.9-2.7 0-1-.2-2-.7-2.8-.5-.8-1.2-1.4-2.1-1.6-1.8-.5-3.8.4-5.2 1.9-2.8 2.9-3.7 7.9-1.6 11.5 1 1.8 2.7 3.3 4.8 3.4 2.1.1 4.3-1 6-2.3'></path></g><path d='m34.3 12.7c0 5.4-4.4 9.7-9.8 9.7-5.4 0-9.8-4.4-9.8-9.7 0-5.4 4.4-9.7 9.8-9.7 5.4 0 9.8 4.4 9.8 9.7' fill='#94d82a'></path><ellipse cx='22.7' cy='13.1' rx='7.4' ry='7.6' fill='#fcfcfa'></ellipse><path d='m29.3 13.1c0 2.9-2.3 5.3-5.1 5.3-2.8 0-5.1-2.4-5.1-5.3 0-2.9 2.3-5.3 5.1-5.3 2.8 0 5.1 2.4 5.1 5.3' fill='#3e4347'></path> </svg>"
url = "https://fivem.net"
weight = 10

[[menu.main]]
name = "Forum"
url = "https://forum.cfx.re"
weight = 20

[[menu.main]]
name = "Discord"
url = "https://discord.gg/fivem"
weight = 30

[[menu.main]]
name = "Servers"
url = "https://servers.fivem.net"
weight = 40

[[menu.main]]
name = "GitHub"
url = "https://github.com/citizenfx/fivem"
weight = 50

[[menu.main]]
name = "Terms of Service"
url = "https://fivem.net/terms"
weight = 60

[[menu.main]]
name = "<svg style='height: 16px; width: 16px;'><use xlink:href='#patreon-logo'></use></svg>"
url = "https://patreon.com/fivem"
weight = 70

[params.ui]
sidebar_menu_compact = true
